shadows = false
borders = "none"

[colors]
background = ["black"]
view = ["black"]
primary = ["white"]
highlight = ["blue"]
directory = ["blue"]
directory-background = ["black"]
files = ["white"]
files-background = ["black"]
